services:
  config-management-app:
    build: .
    ports:
      - "8090:8090"
    environment:
      - GO_ENV=development
    networks:
      - app-network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /app/openapi.yaml
    volumes:
      - ./api:/app:ro
    depends_on:
      - config-management-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
