version: '3.8'

services:
  config-management-app:
    build: .
    ports:
      - "8090:8090"
    environment:
      - GO_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
